# è¡¥å…¨é…ç½®æ–¹æ¡ˆ, æºé“¾æ¥https://starship.rs/config-schema.json
"$schema" = 'file:///home/xujian/.config/starship/config-schema.json'

command_timeout = 2000 # x ms

# æç¤ºç¬¦
format = """
[î‚¶](#9A348E)\
$username\
[î‚°](bg:#DA627D fg:#9A348E)\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$c\
$lua\
$perl\
$python\
$nodejs\
[î‚°](fg:#86BBD8 bg:#06969A)\
$hostname\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚° ](fg:#33658A)\
$cmd_duration
$character
"""
#not support
# right_format = """$battery"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[character]
#success_symbol = "[â¯](purple)"
success_symbol = "[â¯â¯âœ](bold purple)"
error_symbol = "[â¯â¯](red)"
vimcmd_symbol = "[â®â®](green)"

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó±ª "
"æ–‡æ¡£" = "ó±ªš "
"Downloads" = "ï€™ "
"ä¸‹è½½" = "ï€™ "
"Music" = "ï€ "
"éŸ³ä¹" = "ï€ "
"Pictures" = "ï€¾ "
"å›¾ç‰‡" = "ï€¾ "
"Videos" = "ó°•§ "
"è§†é¢‘" = "ó° ¾ "

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 10
style = '#871f24'

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "
style = "bg:#86BBD8"
#format = '[ $symbol ($version) ]($style)'
format = '[ $symbol($version(-$name)) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = "ï˜ "
style = "bg:#ee7755"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ba5b49"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[hostname]
ssh_only = false
format = "[ $hostname ]($style)"
style = "bg:#06969A"

[java]
symbol = "î‰– "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[lua]
#symbol = "î˜  "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[memory_usage]
symbol = "ó°› "

[meson]
symbol = "ó°›± "

[nim]
symbol = "î™· "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
#symbol = "îœ˜ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "î¬© "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "îˆµ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'
#format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[perl]
#symbol = "î© "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[rlang]
symbol = "î¨ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = "î‘ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[spack]
symbol = "ğŸ…¢ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:#33658A"
format = '[ â™¥ $time ]($style)'

[cmd_duration]
format = "[â±  $duration]($style) "
style = "white"

[conda]
format = '[$symbol$environment](#68945c) '
